### ISSUE TITLE
Multiple PCBs in Single Project problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Altium-Designer-addons/scripts-libraries#4]
```
I tried the MultiPCBProject V2.0 scripts on Altium V13.1.2,
but the "SCH_UpdateAllPCBDocuments" function does not work.

The compile mask is not placed over the respective blankets, resulting in all 
components compiled onto all PCBs.

I watched the videos, and I think I did things correctly, but maybe there's an 
Altium Preference setting that needs to be enabled.
```

Original issue reported on code.google.com by `rcd...@gmail.com` on 29 Oct 2013 at 3:52

**Comment by justinmassiot** [comment]
Does anyone know if this issue can be closed? It dates back from 2013...

**Comment by reid-p** [comment]
I just had a go with the MultiPCBProject script and have encountered exactly this problem
The blanket iterator never finds anything.
Using Altium 23.1.1

**Comment by antifar** [comment]
邮件已收到，祝好。^_^

**Comment by reid-p** [comment]
G'day @justinmassiot 

Had a play with the Multi Board project feature. But it doesn't really solve the problem as nicely I think as this script would have.
The design has a pair of PCB and due to mechanical constraints and space I need to shuffle parts from one to the other to get everything to fit. The multi board project just seem to allow for define interconnects and providing some checks, and doing a 3d fit check. Does really help in reassigning parts from one to the other. Well not that I've figured out so far.

**Comment by xjordanx** [comment]
That's true.  It doesn't do "partitioning". I think Zuken might still be the only tool that does that as well as the 3D.I believe it's on Altium's road map, but it will likely be a long time before its implemented. In the meantime perhaps the reuse blocks could be the stepping stone to move parts from one board to another?  Just an idea... Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
-------- Original message --------From: Phil ***@***.***> Date: 3/21/23  4:14 PM  (GMT-08:00) To: Altium-Designer-addons/scripts-libraries ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [Altium-Designer-addons/scripts-libraries] Multiple PCBs in Single Project problem (#4) 
G'day @justinmassiot
Had a play with the Multi Board project feature. But it doesn't really solve the problem as nicely I think as this script would have.
The design has a pair of PCB and due to mechanical constraints and space I need to shuffle parts from one to the other to get everything to fit. The multi board project just seem to allow for define interconnects and providing some checks, and doing a 3d fit check. Does really help in reassigning parts from one to the other. Well not that I've figured out so far.
